Repository akshitagupta15june/PetMe, pull requests merged in 2023-06, with the labels that each got.

#601 fixed[584] bug fixed size of light mood icon
  Assets/Images/moon.svg
Labels: gssoc23, level1

#786 Enhancing visibility and user experience: introducing the scroll-to-feature functionality on hero page
  index.html
  style.css
Labels: gssoc23

#841 Email input UI fix in the footer menu
  src/components/Footer/index.jsx
Labels: gssoc23, level1

#853 Added fade-in for contact form
  index.html
  style.css
Labels: gssoc23, level2

#882 remove duplicate kafka blog
  blog.json
Labels: gssoc23, level1

#903 Changing NavBar height
  navbar.css
Labels: gssoc23, level1

#901 Changes made in blog section
  blog.html
Labels: gssoc23, level1

#900 removed about us from reportstary.html
  reportstary.html
Labels: gssoc23, level1

#898 Modified Volunteer Page Bug Fixed
  volunteer.html
Labels: gssoc23, level1
