Repository akshitagupta15june/PetMe, pull requests merged in 2024-06, with the labels that each got.

#1627 fixed position of help button in sos while scroll
  reportstary.css
Labels: level1, gssoc

#1614 Fix: Position-of-Read
  blog.js
Labels: level1, gssoc

#1607 change in border radium
  introSection.css
Labels: level1, gssoc

#1580 inputBoxForOtherAdded
  reportstary.html
  reportstary.js
Labels: level1, gssoc

#1577 Icon added in all pages
  Assets/Images/logo.png
  adopt.html
  blog.html
  blogs/Phoenix.html
  blogs/abhinav.html
  blogs/abhishek.html
  blogs/alexis.html
  blogs/anuran.html
  blogs/arvind.html
  blogs/dan.html
  blogs/disha.html
  blogs/elise.html
  blogs/elizabeth.html
  blogs/eslem.html
  blogs/manish.html
  blogs/nalowa.html
  blogs/omkar.html
  blogs/pagsum.html
  blogs/prasanna.html
  blogs/rayarka2.html
  blogs/rayarka26.html
  blogs/rayarka3.html
  blogs/shelby.html
  blogs/shruti.html
  blogs/tannistha.html
  blogs/vidhisha.html
  blogs/wesley.html
  donate.html
  donate1.html
  index light.html
  index.html
  logo.png
  news.html
  reportstary.html
  volunteer.html
Labels: level3, gssoc

#1570 docs: update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: level2, gssoc

#1567 Added error msg in form fields in donate.html issue #1537
  donate.html
  output.css
Labels: level1, gssoc

#1566 Phone number validation is added
  adopt.html
Labels: level1, gssoc

#1728 begin blog darkmode
  blog.html
  blogs/blog.css
  light-dark-theme.js
Labels: level2, gssoc

#1741 Update the adopt form
  adopt.html
Labels: ssoc, beginner

#1756 new nav bar
  index.html
  introSection.css
  navbar.css
  style.css
Labels: level1, gssoc

#1768 Updating blog containers and ui changed
  blog.html
Labels: ssoc, beginner

#1807 Added cursor-pointer in "Support-Us" bottom #1798
  blog.html
  donate.html
  index.html
  navbar.css
  news.html
  reportstary.html
  volunteer.html
Labels: level1, gssoc

#1789 fetched and merged
  donate.html
  light-dark-theme.js
Labels: ssoc, beginner

#1786 fix :- #1784 subscribe/footer section text is not visible has been updated
  blog.html
Labels: ssoc, beginner

#1806 Fixed Bug #1779
  index.html
Labels: ssoc, beginner

#1834 fix support and donate
  blog.html
  donate1.html
  light-dark-theme.js
  navbar.css
  volunteer.html
Labels: ssoc, beginner

#1844 Added white color to footer text for visibility
  blog.html
Labels: gssoc

#1845 Changes in UI of nav bar in menu
  index.html
Labels: level1, gssoc

#1871 Updated PetCards section in Dark and LightModes Respectively.
  index.html
  light-dark-theme.js
  style_PetCards.css
Labels: ssoc, intermediate

#1857 #Contact Section background color improved. Now it looks good
  index.html
Labels: level1, gssoc
